kgu-clab/clab-platforms-server

src/main/java/page/clab/api/domain/book/dao/BookLoanRecordRepositoryImpl.java
src/main/java/page/clab/api/domain/book/dto/response/BookLoanRecordResponseDto.java
src/main/java/page/clab/api/domain/login/application/LoginAttemptLogService.java
src/main/java/page/clab/api/domain/login/domain/LoginAttemptLog.java
src/main/java/page/clab/api/global/auth/filter/IpAuthenticationFilter.java
src/main/java/page/clab/api/global/common/dto/IPInfoResponse.java
src/main/java/page/clab/api/global/config/IPInfoConfig.java
src/main/java/page/clab/api/global/config/SecurityConfig.java
src/main/java/page/clab/api/global/config/WebConfig.java
src/main/java/page/clab/api/global/util/HttpReqResUtil.java
src/main/java/page/clab/api/global/util/IPInfoUtil.java

> 기존 GeoIP2 데이터베이스가 다소 부정확한 위치 정보를 반환하여 IPInfo로 서비스를 변경합니다.
매월 5만 건을 무료로 요청할 수 있으며, 초과될 경우 자동으로 위치 조회를 멈추게 설계되었습니다.
- GeoIP2 -> IPInfo 서비스 변경

GeoIP2 -> IPInfo 서비스 변경

---

src/main/java/page/clab/api/domain/blog/domain/Blog.java
src/main/java/page/clab/api/domain/blog/dto/request/BlogRequestDto.java
src/main/java/page/clab/api/domain/blog/dto/request/BlogUpdateRequestDto.java
src/main/java/page/clab/api/domain/blog/dto/response/BlogDetailsResponseDto.java
src/main/java/page/clab/api/domain/blog/dto/response/BlogResponseDto.java

> 기술 블로그 운영 방식을 변경함에 따라 새로운 컬럼을 추가합니다.
기술 블로그에는 핵심 내용만을 요약하여 작성하고, 필요한 경우 유저가 작성자의 블로그로 이동하여 자세한 내용을 살펴볼 수 있도록 합니다.
- 하이퍼링크 기능 추가

기술 블로그 하이퍼링크 기능 추가 완료

---

src/main/java/page/clab/api/domain/book/application/BookLoanRecordService.java
src/main/java/page/clab/api/domain/book/application/BookService.java
src/main/java/page/clab/api/domain/book/dao/BookLoanRecordRepository.java

> #327에 대한 버그를 수정했습니다.
도서대출상태가 APPROVED인 조건을 더 추가해주었습니다.
- 도서반환 및 대출 연장 오류 버그 수정

도서 반환 및 대출 연장 오류 수정 완료

---

src/main/java/page/clab/api/global/common/slack/application/SlackService.java
src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java

> #325
일부 서버 에러에서 슬랙 메시지 전송에 실패하는 문제를 해결합니다.
- ExceptionHandler에 문제가 되던 서버 에러를 추가
- 일부 예외의 파싱 과정에서 발생하는 오류 수정
- 메시지가 정상적으로 보내지지 않던 오류 수정

슬랙 에러 메시지 전송 오류 수정 완료

---

src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java

> #330 
프론트엔드의 핸들링 유용성을 고려하여 일부 에러 코드의 응답을 변경합니다.
- 400 Bad Request 발생시 에러 메시지를 반환
- 404 Not Found 발생시 에러 메시지를 반환

일부 에러 코드에 대한 응답 변경 완료

---

src/main/java/page/clab/api/domain/comment/application/CommentService.java
src/main/java/page/clab/api/domain/comment/dto/response/CommentMyResponseDto.java

> #332 
게시글을 삭제하고 내 댓글을 조회했을 때 NullPointerException이 발생
내 댓글 조회시 삭제된 댓글이 포함되는 문제
- 나의 댓글 조회시 삭제된 게시글이 포함되어 NullPointerException이 발생하는 문제 수정
- 내 댓글 조회시 삭제된 댓글이 포함되는 문제 수정

내 댓글 조회시 발생하는 오류 수정 완료

---

src/main/java/page/clab/api/domain/board/api/BoardController.java
src/main/java/page/clab/api/domain/board/application/BoardService.java
src/main/java/page/clab/api/domain/comment/application/CommentService.java
src/main/java/page/clab/api/domain/comment/dto/response/CommentResponseDto.java

> #334 
클라이언트에서 게시글, 댓글과 관련한 요청을 보낸 후 정보를 재요청할 수 있도록 반환정보를 변경합니다.
댓글이 작성된 일자를 추가로 반환합니다.
-  게시글 생성, 수정, 삭제시 삭제된 게시글의 카테고리가 반환되도록 변경
- 댓글 생성, 수정, 삭제시 게시글의 id를 반환하도록 변경
- 댓글 응답 정보에 생성일자(createdAt) 추가

게시글 및 댓글 반환 정보 수정 완료

---

src/main/java/page/clab/api/global/config/SecurityConstants.java

> #336 
favicon.ico에 대한 접근이 차단되어 비정상적인 접근으로 간주됨.
- favicon.ico 접근 허용

favicon.ico 차단 문제 수정

---

src/main/java/page/clab/api/domain/board/dto/response/BoardCategoryResponseDto.java
src/main/java/page/clab/api/domain/board/dto/response/BoardDetailsResponseDto.java
src/main/java/page/clab/api/domain/board/dto/response/BoardListResponseDto.java
src/main/java/page/clab/api/domain/board/dto/response/WriterInfo.java

> #338 
공지사항이 카테고리인 게시글의 경우, 운영진이 작성한 게시글임을 표시하기 위해 이름을 운영진으로 표기합니다.
- 게시글 조회에서 운영진이 작성한 공지사항 게시글일 경우 응답 정보를 변경
- 기존 익명 처리와 더해져 분기처리가 많아짐에 따라 작성자의 정보를 관리하는 클래스를 작성하여 로직을 분리

공지사항 게시글에 대한 응답 변경 완료

---

src/main/java/page/clab/api/domain/application/domain/Application.java
src/main/java/page/clab/api/domain/login/application/LoginService.java

> #344 
로그인 시스템 개편 이후, 일부 API를 통해 새 멤버를 생성했을 때 OTP 정보가 null로 기입되어 로그인이 되지 않는 현상이 발생하고 있습니다.
- 동아리 지원 이후 합격자에 대한 멤버 생성 API 호출시 OTP 정보를 기입하도록 변경
- OTP 활성 정보가 없는 경우(null인 경우) OTP가 비활성화된 것으로 간주

OTP 활성 정보가 없어 발생하는 로그인 문제 해결

---

src/main/java/page/clab/api/domain/login/application/AccountLockInfoService.java
src/main/java/page/clab/api/domain/login/domain/RedisToken.java
src/main/java/page/clab/api/global/auth/filter/JwtAuthenticationFilter.java
src/main/java/page/clab/api/global/common/slack/application/SlackService.java

> #346 
일부 슬랙 메시지에 대한 개선을 목표로 합니다.
개선 대상은 다음과 같습니다.
- 로그인에 대한 보안 경고
- 템플릿
- 중복 로그인 및 지속적인 로그인 실패에 대한 경고 대상을 관리자 이상의 멤버로 제한
- 중복 로그인 및 지속적인 로그인 실패에 대한 사용자의 정보를 메시지에 표기할 수 있도록 개선
- 미리보기에서 제목 확인이 가능하도록 개선

슬랙 메시지 개선 완료

---

src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java

> #349 
OTP 인증번호에 숫자 이외의 문자열이 포함된 경우 NumberFormatException과 함께 상태코드 500이 반환되고 있습니다.
현재 백엔드 시스템에서 OTP를 제외하더라도 항상 올바른 타입에 대해서만 로직이 실행되도록 하고 있기에 NumberFormatException가 발생한 경우 400 Bad Request로 처리하도록 변경합니다.
- 예외 핸들러에서 NumberFormatException에 대해 400 Bad Request로 응답하도록 변경
변경 전
변경 후

클라이언트 입력값에 대한 처리 개선 완료

---

src/main/java/page/clab/api/domain/board/application/BoardService.java
src/main/java/page/clab/api/domain/board/dto/response/BoardCategoryResponseDto.java

> #356 
ETC에 첨부된 사진과 같이 현재 게시글에 대한 간략한 정보만 응답으로 보내 표시하도록 설계되어있습니다.
글에 들어가지 않더라도, 목록에서 게시글에 작성된 댓글의 개수를 확인할 수 있도록 개선합니다.
- 응답에 댓글 개수 정보 추가

커뮤니티 게시글 조회 API 개선 완료

---

src/main/java/page/clab/api/domain/comment/application/CommentService.java
src/main/java/page/clab/api/domain/comment/domain/Comment.java

> #359 
대댓글의 순서가 오래된 순으로 정렬되어 보이도록 수정했습니다.
대댓글 정렬 순서 어노테이션으로 명시

대댓글의 순서가 정렬되지 않는 버그 해결

---

src/main/java/page/clab/api/domain/login/application/LoginAttemptLogService.java
src/main/java/page/clab/api/global/auth/filter/IpAuthenticationFilter.java
src/main/java/page/clab/api/global/config/SecurityConfig.java
src/main/java/page/clab/api/global/filter/IPinfoSpringFilter.java
src/main/java/page/clab/api/global/util/HttpReqResUtil.java

> #326 
[1]
기존 일부 IP를 대상으로 정적으로 처리하던 사설 IP(Bogon IP) 판별 로직을 강화합니다.
[2]
IP 정보를 가져오는 서비스와 해외 IP를 차단하는 서비스가 강결합되어있다고 판단됩니다.
변경 용이성 및 단일 책임 원칙을 고려하여 각 서비스를 분리하여 필터로 구성합니다.
- Bogon IP 판별 로직 개선
- 요청 IP에 대한 정보 수집/차단 필터 분리
스크린샷의 로그는 테스트 목적으로 임시로 작성한 로그이며, 커밋에 포함되지 않습니다.
`IPinfoSpringFilter`에서 IP 정보를 수집하고 `IpAuthenticationFilter`에서 해외 IP를 차단하는 과정이 순차적, 정상적으로 이루어짐을 확인할 수 있습니다.

IP 지리적 위치 서비스 개선 완료

---

build.gradle
src/main/java/page/clab/api/global/common/file/application/FileHandler.java
src/main/java/page/clab/api/global/config/WebConfig.java
src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java

> #358 
이미지 파일 업로드 시 촬영 각도에 따라 회전하는 버그를 해결했습니다.
- 필요한 의존성을 추가하고 전송된 multipartfile의 회전정보에 따라
적절하게 다시 회전 후 서버에 이미지를 저장합니다.

이미지 파일 업로드 시 회전 버그 해결

---

src/main/java/page/clab/api/global/common/email/application/EmailAsyncService.java
src/main/java/page/clab/api/global/common/email/application/EmailService.java
src/main/java/page/clab/api/global/common/email/domain/EmailTask.java

> #368 
코드를 알아보기 쉽게 개선하고, 이메일 전송 과정에서 스케줄링을 제거하고 비동기 메소드 사용 방식을 수정했습니다.
- EmailTask 분리
- 스케줄링 제거
- Async 관련 메소드 사용 방식 수정 
파일 없이 메일 전송 결과
파일과 함께 메일 전송 결과
일반 메일 전송, 전체 메일 전송 둘 다 결과가 같게 나왔습니다.

이메일 전송 로직 개선 완료

---

jenkins/Jenkinsfile

> #370 
[1]
서버 환경에 따라 Attachment color를 설정하여 알림을 구분할 수 있도록 합니다.
[2]
빌드 성공/실패 여부를 보다 쉽게 구분하기 위해 메시지의 색상을 부여합니다.
[3]
Git 변경 사항을 출력합니다.
- Slack Message에 Attachment 추가
- Jenkins Credentials에 슬랙 메시지 색상 추가
- Git 변경 사항을 가져와 출력하도록 함

젠킨스 슬랙 알림 개선 완료

---

src/main/java/page/clab/api/domain/schedule/application/ScheduleService.java
src/main/java/page/clab/api/domain/schedule/dao/ScheduleRepositoryCustom.java
src/main/java/page/clab/api/domain/schedule/dao/ScheduleRepositoryImpl.java

> #371 
일정 조회 시 자신이 등록하지 않은 일정이 조회가 되지 않는 현상을 해결했습니다.
- ScheduleType이 ALL인 일정을 조회합니다.
- ScheduleType이 Study이거나 Project일 때 본인이 포함된 활동의 일정을 조회합니다.
DAO에서 쿼리문을 작성할 때, where절에 currentMember가 포함되도록 작성되어 있어 발생한 문제였습니다.
이와 같이 superuser가 생성한 일정이 DB에 저장되어 있을 때,
일반 회원이 일정을 조회하면 본인이 활동 중인 C 스터디 하나만 조회가 되고, ScheduleType이 ALL인 모든 일정이 조회됩니다.
```json
{
"data": {
"totalItems": 6,
"take": 6,
"items": [
{
"id": 10,
"title": "코어팀 2기 면접",
"detail": "C-Lab Core Team 2기 (Front, Back)의 대면 면접이 있습니다. 13:00~13:50 동안 진행되며 팀당 약 10분씩 소요될 예정입니다.",
"activityName": null,
"startDate": "2024-05-27T13:00:00",
"endDate": "2024-05-27T13:50:00",
"priority": "HIGH"
},
{
"id": 11,
"title": "코어팀 2기 합격 발표",
"detail": "C-Lab Core Team 2기 …
```

일정 조회가 되지 않는 현상 해결

---

src/main/java/page/clab/api/global/common/email/application/EmailAsyncService.java
src/main/java/page/clab/api/global/common/email/application/EmailService.java

> #375 
지원 단위 별로 합격자 계정 통합 생성시 이메일이 정상적으로 보내지지 않는 현상을 해결했습니다.
- EmailService에 있던 emailQueue를, 실제 사용하는 EmailAsyncService로 옮깁니다.
- processEmileQueue에 스케줄러를 다시 도입합니다.
이전에 해당 부분을 리팩토링했을 때, 시스템 성능을 위해 스프링의 스케줄러를 삭제했습니다. 하지만 스케줄러를 삭제하니 EmailTask가 emailQueue에 저장되었다가 processEmailQueue 메소드에 의해 실제 이메일이 전송되는 과정에서, 비동기로 실행하기 때문에 다른 비동기 작업들이 완료되지 않아 첫 api 호출에서 이메일 큐의 내용을 처리하지 못하는 문제로 발생한 버그로 인지했습니다. 
따라서 다시 스프링 스케줄러를 도입해 비동기 메소드를 주기적으로 호출해 큐에 남아있는 이메일들을 계속해서 전송하는 방식으로 변경했습니다.
여러 번 계정 삭제 및 반복으로 전송을 시도했을 때, 잘 전송이 되는 것을 볼 수 있습니다.

지원단위별 계정 통합 생성 시 이메일이 보내지지 않는 현상 해결

---

.gitignore
build.gradle
jenkins/Jenkinsfile
src/main/java/page/clab/api/global/auth/application/WhitelistService.java
src/main/java/page/clab/api/global/config/AuthenticationConfig.java
src/main/java/page/clab/api/global/config/SecurityConfig.java
src/main/java/page/clab/api/global/config/WhitelistAccountProperties.java
src/main/java/page/clab/api/global/config/WhitelistPatternsProperties.java
src/main/java/page/clab/api/global/util/SwaggerUtil.java
src/main/resources/logback-spring.xml

> #348 
모니터링 시스템 도입은 다음의 목표를 가집니다.
1. 로그를 중앙에서 관리하고 시각화하여 보다 쉽게 접근하고 활용할 수 있도록 합니다.
2. 사용자의 행동 패턴을 분석합니다.
3. 시스템 상태를 실시간으로 모니터링하고, 문제 발생 시 빠르게 대응할 수 있도록 합니다.
4. 시스템 로그를 통해 보안 이벤트를 모니터링하고 감사 로그를 관리합니다.
---
Actuator 접근 제어를 위해, 화이트리스트 기능이 보다 범용성있게 작동할 수 있도록 수정하였습니다.
- Logback 설정
- Actuator 설정
- Actuator 접근 제어
- 서버 메트릭 수집(Prometheus, Node Exporter)
- 로그 수집(Promtail, Loki)
- 시각화(Grafana)
- 도메인 설정(접근 제어 포함)
관련 파일은 [core-team Repository](https://github.com/KGU-C-Lab/core-team/tree/main/private/common/monitoring)에 업로드 되었습니다.

모니터링 시스템 도입 완료

---

src/main/java/page/clab/api/global/auth/filter/IpAuthenticationFilter.java

> #377 
현재 접근 허용 국가 목록이 코드 내에 하드코딩되어 있어, 목록에 변경 사항이 생길 때마다 코드 수정이 필요합니다.
이는 개발의 유연성을 저해하며, 서버 환경에 따라 관리하기 어렵기에 개선하고자 합니다.
- 접근 허용 국가를 프로파일에서 관리하도록 변경
[프로파일 변경사항 다운로드](https://github.com/KGU-C-Lab/core-team/tree/main/common/profile)

IpAuthenticationFilter 개선 완료

---

jenkins/Jenkinsfile

> #381 
젠킨스 빌드 성공/실패 시 발생하는 메시지의 포맷을 표준화합니다.
이 작업은 Spring 애플리케이션에서 전송하는 메시지와의 포맷 통일과 보다 쉬운 로그 확인을 목표로 합니다.
- Slack Block Kit을 이용한 빌드 메시지 전송
- Job, Console Output 버튼 추가
- 페이로드를 JSON 객체로 정의하여 쉽게 변경 가능하도록 함
빌드 실패시 추가적인 정보를 메시지로 보내려 했으나, 젠킨스에서 전역 변수로 지원하지 않아 제외함.
[Global Variable Reference](https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#using-environment-variables)

젠킨스 슬랙 메시지 개선 완료

---

jenkins/Jenkinsfile

> #383 
젠킨스를 Freestyle에서 Pipeline으로 마이그레이션한 이후, 웹훅이 정상적으로 작동하지 않습니다.
브랜치의 변경 사항을 감지하고 자동으로 빌드 및 배포할 수 있도록 오류를 수정합니다.
- Jenkinsfile에 트리거를 추가하여 Github Webhook이 정상 작동하도록 수정
- Jenkins 접근 제어로 인한 웹훅 푸시 오류 수정
[1]
Freestyle과 달리 Pipeline에서는 Jenkinsfile에서 트리거를 추가해야만 정상적으로 Webhook을 수신하고 빌드합니다. Pipeline에 아래 코드를 추가함으로써 문제를 해결합니다.
```
triggers {
githubPush()
}
```
[2]
지난 #348 작업을 하며 Nginx에서 Jenkins와 Grafana 서비스에 대한 접근 권한을 수정하였습니다. 해당 작업 이후, Github Webhook의 요청이 Nginx에서 차단되는 문제가 발생하였으며, Whitelist에 Github가 사용하는 IP 대역을 추가하여 해결했습니다.
[Jenkins 접근 제어로 인한 깃허브 웹훅 연결 오류 문제 수정](https://github.com/KGU-C-Lab/core-team/commit/db083284d1dcb35b92d4a052e5a057f51934f725)

젠킨스 웹훅 미작동 오류 수정 완료

---

src/main/java/page/clab/api/domain/recruitment/application/RecruitmentService.java
src/main/java/page/clab/api/domain/recruitment/domain/Recruitment.java
src/main/java/page/clab/api/domain/recruitment/domain/RecruitmentStatus.java
src/main/java/page/clab/api/domain/recruitment/dto/request/RecruitmentRequestDto.java
src/main/java/page/clab/api/domain/recruitment/dto/request/RecruitmentUpdateRequestDto.java
src/main/java/page/clab/api/domain/recruitment/dto/response/RecruitmentResponseDto.java
src/main/java/page/clab/api/global/config/TransactionConfig.java
src/main/resources/messages.properties

> #353
원래 모집 공고의 상태를 직접 String으로 수정해야 하는 문제점이 있었습니다.
따라서 모집 시작 시각, 모집 종료 시각을 기준으로 모집 공고의 상태를 자동으로 변경하는 로직을 구현했습니다.
- 모집 공고 상태 enum 마련
- 모집 공고 상태 자동 변경 스케줄링 구현
스케줄링을 사용하는 로직에서 Transaction 어노테이션을 적용하면, 변경 객체가 준영속상태가 되는 문제가 있었습니다.
따라서 스케줄링 로직과 Transaction 어노테이션이 동시에 돌아가지 않는 이슈로 인해 직접 객체의 변경 사항을 커밋했습니다.
*현재시각 < 모집 시작시각*
*모집 시작시각 < 현재시각 < 모집 종료시각*
*현재시각 > 모집 종료시각*
*모집공고 조회*
*모집공고 일정 수정 전*
*모집공고 일정 수정 후(기간 연장)*
-> 다시 open 상태로 즉각 변경됨

모집공고 상태 자동변경 로직 작성 완료

---

src/main/java/page/clab/api/domain/recruitment/domain/RecruitmentStatus.java
src/main/java/page/clab/api/domain/recruitment/dto/response/RecruitmentResponseDto.java

> #393 
클라이언트에서 현재 모집공고 상태의 key를 다른 값으로 매핑하지 못하는 문제로 인해, 
응답으로 discription을 반환하는 것으로 수정했습니다.
- RecruitmentStatus의 discription 변경
- RecruitmentResponseDto의 status 값을 discription으로 반환

모집 공고 상태 응답값 변경 완료

---

build.gradle
src/main/java/page/clab/api/global/auth/jwt/JwtTokenProvider.java

> #420
- Dependabot에 의해 io.jsonwebtoken:jjwt 의존성이 0.11.5에서 0.12.6으로 업데이트되었습니다.
- 업데이트 이후, 서버 로그인 과정에서 Jwts.parserBuilder()가 Jwts.parser()로 변경되면서 로그인 오류가 발생했습니다.
- 이 PR은 해당 변경 사항을 반영하고, 로그인 오류를 해결하기 위한 수정 사항을 포함하고 있습니다.
- `Jwts.parserBuilder()`를 `Jwts.parser()`로 변경된 사항 수정
- JWT 파싱 및 검증 로직 수정

의존성 업데이트로 인한 JWT 파싱 오류 수정 완료

---

src/main/java/page/clab/api/domain/community/board/application/service/BoardDetailsRetrievalService.java
src/main/java/page/clab/api/domain/community/board/application/service/BoardRetrievalService.java
src/main/java/page/clab/api/domain/community/board/application/service/BoardsByCategoryRetrievalService.java
src/main/java/page/clab/api/domain/community/board/application/service/DeletedBoardsRetrievalService.java

> #422 
`BoardRetrievalService`, `DeletedBoardsRetrievalService`, `BoardsByCategoryRetrievalService`, `BoardDetailsRetrievalService`에서, 작성자의 정보를 currentMemberInfo로 받는 것에서 해당 글의 작성자가 되도록 수정했습니다.
- `BoardRetrievalService` 수정
- `DeletedBoardsRetrievalService` 수정
- `BoardsByCategoryRetrievalService` 수정
- `BoardDetailsRetrievalService` 수정
- 게시글 목록, 커뮤니티 별 게시글 목록, 삭제된 게시글 목록 조회
- 게시글 상세 내용 조회

커뮤니티 게시글 작성자가 로그인 된 본인으로 응답되는 버그 해결

---

src/main/java/page/clab/api/global/config/WebConfig.java

> #431 
이 PR은 Cache-Control 설정을 추가하여 서버에서 제공하는 파일의 캐싱을 최적화하는 작업을 포함합니다. 이를 통해 파일 접근 시 성능을 향상시키고, 불필요한 서버 요청을 줄여 서버 부하를 감소시킵니다.
- WebConfig 클래스에 Cache-Control 설정 추가
- 응답 헤더에 Cache-Control 설정이 적용되었는지 확인
- 캐시가 설정된 파일에 접근하여 성능 최적화 확인
```
2024-07-27 16:59:14.151 [http-nio-8080-exec-1] INFO  p.c.a.g.h.ApiLoggingInterceptor - [0:0:0:0:0:0:0:1:anonymousUser] /resources/files/profiles/202310000/1255299469048375_896b6bd5-8fb7-4e76-ac93-2a42aac385b4.jpg GET 200 7ms
2024-07-27 16:59:14.266 [http-nio-8080-exec-4] INFO  p.c.a.g.h.ApiLoggingInterceptor - [0:0:0:0:0:0:0:1:anonymousUser] /resources/files/profiles/202310000/1255299469048375_896b6bd5-8fb7-4e76-ac93-2a42aac385b4.jpg GET 200 4ms
2024-07-27 16:59:19.600 [http-nio-8080-exec-5] INFO  p.c.a.g.h.ApiLoggingInterceptor - …
```

Cache-Control 설정을 통한 파일 캐싱 최적화 완료

---

src/main/java/page/clab/api/global/common/file/domain/UploadedFile.java

> #433 
- 업로드 파일 정보를 가져오지 못하는 오류를 해결합니다.
- 특정 API 호출 시 발생하는 SQL 오류를 수정합니다.
- uploaded_file 테이블에 member_id 컬럼 정보 추가

업로드 파일 정보를 가져오지 못하는 오류 수정

---

src/main/java/page/clab/api/domain/community/jobPosting/adapter/in/web/JobPostingDetailsRetrievalController.java
src/main/java/page/clab/api/domain/community/jobPosting/adapter/in/web/JobPostingsByConditionsRetrievalController.java
src/main/java/page/clab/api/domain/community/jobPosting/adapter/out/persistence/JobPostingMapper.java
src/main/java/page/clab/api/domain/community/jobPosting/adapter/out/persistence/JobPostingPersistenceAdapter.java
src/main/java/page/clab/api/domain/community/jobPosting/adapter/out/persistence/JobPostingRepository.java
src/main/java/page/clab/api/domain/community/jobPosting/adapter/out/persistence/JobPostingRepositoryCustom.java
src/main/java/page/clab/api/domain/community/jobPosting/adapter/out/persistence/JobPostingRepositoryImpl.java
src/main/java/page/clab/api/domain/community/jobPosting/application/dto/response/JobPostingDetailsResponseDto.java
src/main/java/page/clab/api/domain/community/jobPosting/application/dto/response/JobPostingResponseDto.java
src/main/java/page/clab/api/domain/community/jobPosting/application/port/in/RetrieveJobPostingDetailsUseCase.java
src/main/java/page/clab/api/domain/community/jobPosting/application/port/in/RetrieveJobPostingsByConditionsUseCase.java
src/main/java/page/clab/api/domain/community/jobPosting/application/port/out/RetrieveJobPostingPort.java
src/main/java/page/clab/api/domain/community/jobPosting/application/service/JobPostingDetailsRetrievalService.java
src/main/java/page/clab/api/domain/community/jobPosting/application/service/JobPostingsByConditionsRetrievalService.java
src/main/java/page/clab/api/domain/community/news/adapter/in/web/NewsByConditionsRetrievalController.java
src/main/java/page/clab/api/domain/community/news/adapter/in/web/NewsDetailsRetrievalController.java
src/main/java/page/clab/api/domain/community/news/adapter/out/persistence/NewsMapper.java
src/main/java/page/clab/api/domain/community/news/adapter/out/persistence/NewsPersistenceAdapter.java
src/main/java/page/clab/api/domain/community/news/adapter/out/persistence/NewsRepository.java
src/main/java/page/clab/api/domain/community/news/adapter/out/persistence/NewsRepositoryCustom.java
src/main/java/page/clab/api/domain/community/news/adapter/out/persistence/NewsRepositoryImpl.java
src/main/java/page/clab/api/domain/community/news/application/dto/response/NewsDetailsResponseDto.java
src/main/java/page/clab/api/domain/community/news/application/dto/response/NewsResponseDto.java
src/main/java/page/clab/api/domain/community/news/application/port/in/RetrieveNewsByConditionsUseCase.java
src/main/java/page/clab/api/domain/community/news/application/port/in/RetrieveNewsDetailsUseCase.java
src/main/java/page/clab/api/domain/community/news/application/port/out/RetrieveNewsPort.java
src/main/java/page/clab/api/domain/community/news/application/service/NewsByConditionsRetrievalService.java
src/main/java/page/clab/api/domain/community/news/application/service/NewsDetailsRetrievalService.java

> #444 
코드베이스에서 미사용 도메인 및 API 정리 과정에서 실수로 삭제된 API를 복원합니다.
- 뉴스 조회 API 복원
- 모든 뉴스 조회: `@GetMapping("/api/v1/news")`
- 특정 뉴스 조회: `@GetMapping("/api/v1/news/{newsId}")`
- 채용 공고 조회 API 복원
- 모든 채용 공고 조회: `@GetMapping("/api/v1/jobPosting")`
- 특정 채용 공고 조회: `@GetMapping("/api/v1/jobPosting/{jobPostingId}")`

채용공고, 뉴스 복원 완료

---

src/main/java/page/clab/api/global/auth/jwt/JwtTokenProvider.java
src/main/java/page/clab/api/global/config/SecurityConfig.java

> #450 
현재 'io.jsonwebtoken' 라이브러리가 0.12.x 버전으로 업데이트되면서 기존에 사용하던 JWT 생성 및 파싱 관련 메소드들이 Deprecate 되었습니다. 이에 따라 최신 버전에 맞춰 Deprecate된 로직을 마이그레이션합니다.
추가로, ROLE_ prefix 설정 로직을 개선합니다.
- Deprecate된 메소드 사용 부분을 새로운 메소드로 변경
- `ROLE_` prefix 설정 로직 개선
[Java JWT: JSON Web Token for Java and Android](https://github.com/jwtk/jjwt)

'io.jsonwebtoken ' 0.12.x 업데이트에 따른 JWT 생성 및 파싱 로직 마이그레이션 완료

---

src/main/java/page/clab/api/domain/members/membershipFee/adapter/in/web/MembershipFeeUpdateController.java

> #461 
기존에는 SUPER 권한을 가진 사용자만 회비 정보를 수정하고 승인할 수 있었기에,
ADMIN 권한을 가진 운영진의 회비 승인 처리가 불가능했습니다. 이에 SUPER -> ADMIN으로 권한을 수정하고자 합니다.
-  회비 정보 수정 권한 ADMIN으로 수정
main 까지 머지가 되어야 해당 수정이 실서비스에 적용될 것 같은데 develop -> main PR을 하나 올려야 될까요?

회비 정보 수정 권한 ADMIN으로 수정 완료

---

src/main/java/page/clab/api/domain/community/board/application/service/BoardRegisterService.java
src/main/java/page/clab/api/domain/members/membershipFee/application/service/MembershipFeeRegisterService.java
src/main/java/page/clab/api/global/common/slack/application/SlackService.java
src/main/java/page/clab/api/global/common/slack/application/SlackServiceHelper.java
src/main/java/page/clab/api/global/common/slack/domain/AlertTypeConverter.java
src/main/java/page/clab/api/global/common/slack/domain/ExecutivesAlertType.java
src/main/java/page/clab/api/global/common/slack/domain/GeneralAlertType.java
src/main/java/page/clab/api/global/common/slack/domain/SlackBoardInfo.java
src/main/java/page/clab/api/global/common/slack/domain/SlackMembershipFeeInfo.java
src/main/java/page/clab/api/global/common/slack/event/NotificationEvent.java
src/main/java/page/clab/api/global/common/slack/listener/NotificationListener.java
src/main/java/page/clab/api/global/config/SlackConfig.java

> #464
운영진들이 회비 신청, 신규 게시글 작성, 동아리 신청 등의 내역을 실시간으로 확인하고 대응할 수 있도록, 관련 내역을 운영진 전용 슬랙 채널로 자동 알림을 보내는 기능을 추가하였습니다.
- 회비 신청 자동 알림
- 회비 신청이 들어올 경우, 신청자의 상세 정보를 포함하여 운영진 전용 슬랙 채널로 자동으로 알림이 전송되도록 구현하였습니다.
- 신규 게시글 알림
- 동아리 홈페이지에 신규 게시글이 작성될 때 운영진 전용 슬랙 채널로 자동 알림이 전송되도록 구현하였습니다.
- 게시글의 제목과 작성자의 이름 등이 포함된 알림 내용 구성을 완료하였습니다.
- 동아리 신청 알림
- 신규 동아리 신청이 있을 경우, 신청자의 기본 정보와 함께 운영진 전용 슬랙 채널로 알림이 전송되도록 구현하였습니다.
- 운영진 전용 슬랙 채널 설정
- 운영진만 접근할 수 있는 슬랙 채널을 별도로 만들어, 모든 알림이 해당 채널로만 가도록 설정하였습니다.
- 알림 기능 테스트 및 피드백 반영
- 슬랙 API를 활용하여 각 알림 기능이 제대로 동작하는지 테스트 진행하였고, 알림 내용 검토 후 피드백을 반영하여 개선 작업을 완료하였습니다.
- 개인정보 보호
- 슬랙 알림 시 개인정보 보호를 위해 계좌 정보 및 기타 민감한 정보는 포함하지 않도록 철저히 관리하였습니다.
- 알림 통합 관리
- 다양한 알림이 운영진 전용 슬랙 채널로 일원화되므로, 혼란이 없도록 알림 내용과 형식을 통일하였습니다.

운영진 슬랙 알림 기능 추가 완료

---

src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java

> #468 
`@PreAuthorize`에서 발생하는 권한 부족 예외를 처리하여, 기존 401 상태 코드 대신 403 상태 코드를 반환하도록 리팩토링하였습니다. 이로써 인증된 사용자가 권한이 부족할 때 올바르게 403 상태 코드가 반환되도록 개선되었습니다.
- 기존의 예외 처리 로직에서 401 반환 부분을 403으로 변경
- [HTTP 상태 코드](https://developer.mozilla.org/ko/docs/Web/HTTP/Status)

`@PreAuthorize`를 통한 API 권한 검사 시 403 상태코드 반환하도록 변경 완료

---

build.gradle
src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupAdminController.java
src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupBoardController.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/ActivityGroupBoardReferenceDto.java
src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/ActivityGroupBoardStatusUpdatedResponseDto.java

> #467 
프론트 @Jeong-Ag님이 활동 그룹 부분의 API 연동 작업을 하시면서 응답으로 반환되는 값 또는 DTO의 수정을 원하셨습니다. 관련된 내용을 작업한 PR 입니다.
- 활동 그룹 게시판 생성, 삭제, 수정 API의 반환값을 id, groupId, parentId로 수정
- 신청 멤버 상태 변경 API의 반환값을 groupId로 수정
- 활동 상태 변경 API의 반환값을 groupId, status로 수정. 이때 groupId 값은 id 변수명으로 매핑
**활동 상태 변경 시 반환값으로 groupId, status 전달**
**활동 그룹 게시판 생성 시 id, groupId, parentId 전달**
**활동 그룹 게시판 수정 시 id, groupId, parentId 전달**
**활동 그룹 게시판 삭제 시 id, groupId, parentId 전달**
**신청 멤버 상태 변경 시 groupId 전달**

feat: 활동 그룹 관련 API 응답 내용 수정 완료

---

src/main/java/page/clab/api/domain/memberManagement/member/adapter/in/web/MemberRoleInfoRetrievalController.java
src/main/java/page/clab/api/domain/memberManagement/member/adapter/in/web/MemberRoleManagementController.java
src/main/java/page/clab/api/domain/memberManagement/member/adapter/out/persistence/MemberPersistenceAdapter.java
src/main/java/page/clab/api/domain/memberManagement/member/adapter/out/persistence/MemberRepositoryCustom.java
src/main/java/page/clab/api/domain/memberManagement/member/adapter/out/persistence/MemberRepositoryImpl.java
src/main/java/page/clab/api/domain/memberManagement/member/application/dto/request/ChangeMemberRoleRequest.java
src/main/java/page/clab/api/domain/memberManagement/member/application/dto/response/MemberRoleInfoResponseDto.java
src/main/java/page/clab/api/domain/memberManagement/member/application/exception/InvalidRoleChangeException.java
src/main/java/page/clab/api/domain/memberManagement/member/application/port/in/ManageMemberRoleUseCase.java
src/main/java/page/clab/api/domain/memberManagement/member/application/port/in/RetrieveMemberRoleInfoUseCase.java
src/main/java/page/clab/api/domain/memberManagement/member/application/port/out/RetrieveMemberPort.java
src/main/java/page/clab/api/domain/memberManagement/member/application/service/MemberRoleInfoRetrievalService.java
src/main/java/page/clab/api/domain/memberManagement/member/application/service/MemberRoleManagementService.java
src/main/java/page/clab/api/domain/memberManagement/member/domain/Member.java
src/main/java/page/clab/api/domain/memberManagement/member/domain/Role.java
src/main/java/page/clab/api/global/common/slack/domain/SecurityAlertType.java
src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java

> #463 
API를 통한 사용자 권한 관리 및 회원 정보 제공 기능을 완료하였습니다. 이 기능은 권한을 관리하는 API와 회원 정보를 제공하는 API를 포함하며, 권한 변경 시 슬랙 알림 기능도 포함되어 있습니다.
- 사용자 권한을 관리할 수 있는 API 구현
- 회원 정보(학번, 이름, 권한) 제공 API 구현
- 권한 변경 시 슬랙 알림 연동
- 보안을 위해 SUPER 권한 사용자만이 해당 API를 호출할 수 있도록 제한

feat: API를 통한 사용자 권한 관리 및 회원 정보 제공 완료

---

src/main/java/page/clab/api/domain/library/bookLoanRecord/application/service/BookLoanRequestService.java
src/main/java/page/clab/api/global/common/slack/application/SlackService.java
src/main/java/page/clab/api/global/common/slack/application/SlackServiceHelper.java
src/main/java/page/clab/api/global/common/slack/domain/ExecutivesAlertType.java
src/main/java/page/clab/api/global/common/slack/domain/SlackBookLoanRecordInfo.java

> #472 
운영진들이 도서 대여 신청 내역을 실시간으로 확인할 수 있도록, 도서 대여 신청 시 운영진 전용 슬랙 채널로 알림을 보내는 기능을 추가했습니다.
- 도서 대여 신청 알림 자동화
- 도서 대여 신청이 들어올 경우, 신청자의 기본 정보와 함께 운영진 전용 슬랙 채널로 알림이 자동으로 전송되도록 구현.
- 운영진 채널 슬랙 알림 한글화

feat(Slack): 도서 대여 신청 운영진 슬랙 알림 기능 추가 완료

---

src/main/java/page/clab/api/domain/hiring/application/application/dto/response/ApplicationPassResponseDto.java
src/main/java/page/clab/api/domain/hiring/application/application/exception/RecruitmentEndDateExceededException.java
src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationPassCheckService.java
src/main/java/page/clab/api/domain/hiring/recruitment/adapter/in/web/RecentRecruitmentsRetrievalController.java
src/main/java/page/clab/api/domain/hiring/recruitment/adapter/out/persistence/RecruitmentPersistenceAdapter.java
src/main/java/page/clab/api/domain/hiring/recruitment/adapter/out/persistence/RecruitmentRepository.java
src/main/java/page/clab/api/domain/hiring/recruitment/application/dto/response/RecruitmentEndDateResponseDto.java
src/main/java/page/clab/api/domain/hiring/recruitment/application/port/in/RetrieveRecentRecruitmentsUseCase.java
src/main/java/page/clab/api/domain/hiring/recruitment/application/port/out/RetrieveRecruitmentPort.java
src/main/java/page/clab/api/domain/hiring/recruitment/application/service/RecentRecruitmentsRetrievalService.java
src/main/java/page/clab/api/domain/hiring/recruitment/domain/Recruitment.java
src/main/java/page/clab/api/domain/hiring/recruitment/domain/RecruitmentStatus.java
src/main/java/page/clab/api/global/config/SecurityConstants.java
src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java

> #479 
모집 공고 절차가 추가됨에 따라, 서버와 클라이언트 간의 통신을 명확히 하기 위한 API 구현 및 로직 개선 작업을 완료했습니다.
1. **최근 일주일 동안의 모집 공고 목록 반환 API 구현**
- 모집 기간 종료일을 기준으로 최근 일주일 동안의 모집 공고 목록을 반환하는 API를 구현했습니다.
- 클라이언트는 이 API를 통해 최신 모집 공고를 조회하고 사용자에게 표시할 수 있습니다.
2. **합격 여부 조회 기능 개선**
- 클라이언트에서 특정 모집 공고 ID와 지원자의 학번 정보를 서버로 전달하면, 서버는 해당 모집 공고에 대한 합격 여부를 반환합니다.
- 모집 공고가 종료된 지 일주일이 지난 경우에는 해당 공고에 대한 조회가 불가능하도록 처리했습니다.
3. **로직 개선 및 예외 처리**
- 서버에서 모집 공고의 종료일을 기준으로 일주일이 지난 경우, 조회 시 예외가 발생하도록 로직을 추가했습니다.
- 이를 통해 잘못된 정보가 클라이언트에 표시되는 것을 방지합니다.
- 추가된 예외 처리 로직에 대한 문서를 작성했습니다.

feat: 모집 공고 절차 추가 및 관련 API 구현 완료

---

src/main/java/page/clab/api/domain/library/book/application/service/BookDetailsRetrievalService.java
src/main/java/page/clab/api/domain/library/book/application/service/BooksByConditionsRetrievalService.java
src/main/java/page/clab/api/domain/library/bookLoanRecord/application/service/BookLoanApprovalService.java
src/main/java/page/clab/api/external/library/bookLoanRecord/application/port/ExternalRetrieveBookLoanRecordUseCase.java
src/main/java/page/clab/api/external/library/bookLoanRecord/application/service/ExternalBookLoanRecordRetrievalService.java

> #482 
도서 대출시, 책의 대출자 정보(`borrowerId`, `borrowName`)가 도서를 승인해주는 관리자의 정보로 저장되는 버그를 수정했습니다.
- 도서 승인시, 대출자 정보가 승인자 정보로 저장되는 로직 수정
`202014941 송재훈`이 도서 대출을 하고, 관리자가 승인한 후, 도서 목록 조회를 한 원래의 결과입니다.
- 도서 목록 조회
- 도서 상세 조회

fix: 도서 대출시 도서의 대출자 정보가 승인자로 저장되는 버그 수정 완료

---

src/main/java/page/clab/api/domain/memberManagement/member/adapter/in/web/MemberRoleInfoRetrievalController.java
src/main/java/page/clab/api/domain/memberManagement/member/adapter/out/persistence/MemberPersistenceAdapter.java
src/main/java/page/clab/api/domain/memberManagement/member/application/port/in/RetrieveMemberRoleInfoUseCase.java
src/main/java/page/clab/api/domain/memberManagement/member/application/port/out/RetrieveMemberPort.java
src/main/java/page/clab/api/domain/memberManagement/member/application/service/MemberRoleInfoRetrievalService.java

> #491 
멤버 권한 조회 API에서 타입 지정 문제로 인해 메타데이터가 누락되는 문제를 수정합니다.
- `retrieveMemberRoleInfo()` 메소드의 반환형을 `PagedResponseDto<MemberRoleInfoResponseDto>`로 수정
```json
{
"data": {
"hasNext": true,
"totalPages": 2,
"totalItems": 6,
"take": 3,
"items": [
{
"id": "201912156",
"name": "홍길동",
"role": "USER"
},
{
"id": "202310000",
"name": "홍길동",
"role": "USER"
},
{
"id": "202310001",
"name": "홍길동",
"role": "USER"
}
]
}
}
```

fix: 멤버 권한 조회 API의 응답에서 메타데이터가 누락되는 문제 수정 완료

---

src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupBoardController.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
src/main/java/page/clab/api/domain/activity/activitygroup/dao/ActivityGroupBoardRepository.java
src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepository.java
src/main/java/page/clab/api/domain/activity/activitygroup/domain/ActivityGroupBoardCategory.java
src/main/java/page/clab/api/domain/activity/activitygroup/exception/AlreadySubmittedThisWeekAssignmentException.java
src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java

> #500 
1. 과제 제출을 한 사람이 여러 번 할 수 있는 문제로 인해, 과제 제출을 1회만 가능하도록 validation을 추가했습니다.
2. 게시물의 카테고리별 권한 제어 로직을 작성했습니다.
- 게시물 생성
- 카테고리가 `NOTICE`, `WEEKLY_ACTIVITY`,  `ASSIGNMENT`, `FEEDBACK`인 경우에, 권한이 ADMIN 이상이거나, 그룹의 리더만 게시물을 작성할 수 있도록 작성했습니다.
- 게시물 조회
- 카테고리가 SUBMIT이거나 FEEDBACK일 시, 과제 제출자 혹은 그룹의 리더만이 해당 게시물에 접근 가능하도록 작성했습니다.
- 과제 제출을 1회만 가능하도록 validation 추가
- 과제 수정 시 updatedAt 정보가 수정되는지 확인
- 게시글 카테고리별 생성 권한 제어
- 게시글 카테고리별 조회 권한 제어
과제 수정 시, updatedAt 정보가 정상적으로 수정됨을 확인했습니다.
```
{
"data": {
"totalItems": 3,
"take": 3,
"items": [
{
"id": 4,
"memberId": "202014941",
"memberName": "송재훈",
"parentId": 3,
"category": "SUBMIT",
"title": "202014941 1주차 과제 제출",
"content": "1주차 과제 제출하도록 하겠습니다.",
"files": [], …
```

refactor: QA 피드백에 따른 활동 게시판 로직 수정 완료

---

src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepository.java

> #501 
활동 게시판 생성시 "새 게시글"이라는 멘트를 카테고리명으로 수정하였습니다.
활동 게시판 생성 알림을 팀원, 팀장별로 다르게 전송하도록 하였습니다.
팀장의 경우 본인이 등록한 게시글 이외의 모든 새 게시글 알림을 받고,
팀원의 경우 팀장이 등록하는 주차별 활동, 과제, 본인 과제에 대한 피드백 알림을 받습니다.
따라서 다른 팀원이 과제를 등록한 것과 팀장이 다른 팀원의 과제에 피드백한 알림은 받지 않습니다.
- 카테고리에 따른 알림 전송 대상 제어
- 활동 관련 알림에 "새 게시글"을 카테고리명으로 변경
해당 작업에서 활동 그룹에 참여 승인된 즉, 실제 활동 멤버를 List 값으로 받기 위해 아래와 같은 메소드를 작성했습니다. 아마 다른 수정사항들 작업하실 때 필요할 것 같습니다. 참고해주세요!
`List<GroupMember> findAllByActivityGroupIdAndStatus(Long activityGroupId, GroupMemberStatus status);`
현재 202211522, 202211523 학생이 팀원으로 참여하고 있는 활동입니다. 팀장의 주차별활동, 과제는 두 사람 모두 받지만 202211523 학생의 제출알림은 팀장에게만, 팀장이 202211523 학생에게 피드백을 단 것은 202211523 학생만 알림을 받을 수 있습니다.

refactor : 활동 도메인에서 발생하는 알림 내용 수정 완료

---

src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepository.java
src/main/java/page/clab/api/global/auth/filter/FileAccessControlFilter.java
src/main/java/page/clab/api/global/auth/util/AuthUtil.java
src/main/java/page/clab/api/global/common/file/application/FileService.java
src/main/java/page/clab/api/global/config/SecurityConfig.java
src/main/java/page/clab/api/global/config/WebConfig.java

> #502
업로드된 파일에 URL로 접근할 때 파일 카테고리마다 적절한 접근 기준에 따라 파일을 반환하도록 하였습니다. **파일경로에 접근할 때 JWT와 함께 요청**을 보내야 합니다.
- `"boards", "profiles", "activity-photos", "membership-fee"` 의 경우 GUEST 이상인 경우 접근가능
-  `"members"`의 경우 업로드 본인만 접근가능
-  `"assignments"`의 경우 제출자와 스터디장, ADMIN 이상인 경우 접근 가능
업로드된 파일 접근 권한 검사 후 제어
- 해당 작업내용이 적용되면 **파일 접근 시 JWT를 함께 담아서 요청**해야 하는데, 프론트에서 파일 접근 로직에  코드 수정이 일어날 것 같습니다. **제가 구현한 방향이 맞는지 확인부탁드립니다**.
- 활동사진은 GUEST 로그인 이상의 경우 파일 반환
- 개인 클라우드 경로 파일은 본인만 확인가능 아래는 GUEST 로그인한 사용자로 접근한 경우
- 과제의 경우 제출자와 스터디장, ADMIN 사용자만 확인가능

feat: 파일 접근 보안 강화 완료

---

src/main/java/page/clab/api/global/common/slack/application/SlackServiceHelper.java
src/main/java/page/clab/api/global/config/SecurityConfig.java
src/main/java/page/clab/api/global/handler/ApiLoggingInterceptor.java
src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
src/main/java/page/clab/api/global/util/ApiLogger.java

> #509 
현재 엔드포인트에 대한 로깅이 URI까지만 출력되고 있으며, 사용자가 요청한 파라미터는 로그에 포함되지 않고 있습니다. 이로 인해 특히 버그가 발생했을 때 문제를 추적하는 데 어려움이 있습니다. URI에 사용자가 요청한 파라미터를 포함시켜 로그로 출력하여 문제를 더 효과적으로 추적할 수 있도록 개선이 필요합니다.
- 요청 파라미터를 URI에 덧붙여 로그에 출력되도록 수정
- HttpServletRequest에서 요청 파라미터를 추출하여 URI와 함께 로그로 출력
- 예외 발생 시에도 요청 파라미터가 포함된 로그가 출력되도록 로직 추가
- 로깅 형식을 기존 로그와 일관되도록 조정

refactor: 엔드포인트 URI 로깅에 요청 파라미터 추가 완료

---

src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepository.java
src/main/java/page/clab/api/domain/activity/activitygroup/domain/ActivityGroupBoard.java
src/main/java/page/clab/api/domain/activity/review/application/service/ReviewRegisterService.java
src/main/java/page/clab/api/domain/members/schedule/application/service/ScheduleRegisterService.java

> #510  
리더가 여러 명이 될 수 있지만, `GroupMemberRepository`의 `findByActivityGroupIdAndRole`에서는 단일 데이터를 리턴하고 있었습니다.
따라서, 해당 메서드의 반환 타입을 List로 변경하고, 그에 따른 변경점들을 수정했습니다.
- `findByActivityGroupIdAndRole` 반환 타입 List로 수정
- List 타입에 맞게 stream을 이용해 리더 판별
해당 이슈로 인해 오류가 났었던 `활동 그룹 게시판 계층 구조적 조회`에서도 잘 작동하는 걸 확인할 수 있었습니다.
```
{
"data": {
"totalItems": 1,
"take": 1,
"items": [
{
"id": 9,
"memberId": "leader",
"memberName": "리더",
"category": "ASSIGNMENT",
"title": "1주차 과제 제출해주시기 바랍니다.",
"content": "1주차 과제 제출해주세요!",
"dueDateTime": "2024-08-30T15:02:20.623",
"updatedAt": "2024-08-26T00:04:29.000072",
"createdAt": "2024-08-26T00:04:29.000072",
"files": [],
"children": [
{
"id": 10,
"memberId": "202014941",
"memberName": …
```

refactor: 활동 그룹 리더가 여러 명이 될 수 있음에 따른 코드 수정 완료

---

jenkins/prod/Jenkinsfile
jenkins/stage/Jenkinsfile

> #518 
1. 서버 배포시 슬랙 알림을 최소화하고 members와 plus 프로젝트 채널을 구분하고자 했습니다. 이에 웹훅 URL을 두 개 생성해놓았습니다. 
2. 추가로 C-Lab-CoreTeam 슬랙 워크스페이스를 새로 개설하였습니다.
- 새로운 슬랙 워크스페이스 생성
- members와 plus 프로젝트의 슬랙 알림 채널을 구분
- 배포 성공/실패한 경우에만 슬랙에 알림을 전송하도록 변경
members prod config 파일은 따로 관리되는 레포에 올렸습니다.
새로운 슬랙 워크스페이스입니다. 채널이 members, plus로 나눠져 있고, 웹훅 링크도 만들어놓은 상태입니다. 또한 members prod의 경우는 jenkins 관련 config 파일에 members 채널에 연결할 수 있는 링크로 수정해서 환경변수 레포에 올려놨습니다. 
기존의 platforms_prod_config_yml에서 members_prod_config_yml로 수정하였습니다. 또한 실제 yml 파일 내에 새로 만든 워크플레이스의 members 채널에 웹훅을 연결했습니다.

슬랙 알림 최소화 및 채널 구분 완료

---

src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardPersistenceAdapter.java
src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardRepository.java
src/main/java/page/clab/api/domain/community/board/application/port/out/RetrieveBoardPort.java
src/main/java/page/clab/api/external/community/board/application/service/ExternalBoardRetrievalService.java

> #524 
마이페이지 내가 쓴 댓글 조회 시 삭제된 게시글의 댓글도 반환하도록 수정했습니다.
내가 쓴 댓글 조회 시 삭제된 게시글일 경우 board 정보를 찾지 못해 NotFoundException이 발생하였습니다.
그 결과 마이페이지 접속이 안 되는 버그가 발생했습니다.
- 마이페이지 내가 쓴 댓글 조회 시 삭제된 게시글의 댓글도 반환하도록 수정

fix: 삭제된 게시글로 인해 나의 댓글이 조회되지 않는 문제 수정

---

.gitignore
src/main/java/page/clab/api/global/auth/application/IpWhitelistValidator.java
src/main/java/page/clab/api/global/auth/application/WhitelistService.java
src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
src/main/java/page/clab/api/global/auth/filter/JwtAuthenticationFilter.java
src/main/java/page/clab/api/global/auth/util/IpWhitelistValidator.java
src/main/java/page/clab/api/global/auth/util/WhitelistFileLoader.java
src/main/java/page/clab/api/global/config/SecurityConfig.java
src/main/java/page/clab/api/global/config/YamlConfig.java
src/main/java/page/clab/api/global/util/IpAddressUtil.java
src/main/java/page/clab/api/global/util/WhitelistPathMatcher.java
src/main/resources/application.yml

> #527 
이트리스트 관리 방식을 JSON에서 YAML로 전환하고, 서브넷 마스크를 지원하는 기능을 추가했습니다. 이를 통해 IP 관리의 유연성을 높이고, YAML의 가독성과 유지보수성을 활용할 수 있도록 개선하였습니다.
- JSON 파일을 YAML 파일로 변환하여 관리 방식을 개선하였습니다.
- 서브넷 마스크를 지원하여 동일 네트워크 내의 IP 범위를 보다 효율적으로 관리할 수 있도록 기능을 추가하였습니다.
- 파일 접근 시 발생할 수 있는 경합 조건(Race Condition) 문제를 해결하기 위해 Lock을 적용하여 동기화 처리하였습니다.
생성된 `whitelist.yml`

refactor: 화이트리스트 관리 방식 JSON → YAML 전환 및 서브넷 마스크 지원 기능 추가 완료

---

src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupAdminController.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
src/main/java/page/clab/api/domain/activity/activitygroup/domain/GroupMemberStatus.java
src/main/java/page/clab/api/domain/activity/activitygroup/exception/SingleLeaderModificationException.java
src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java

> #532 
활동 도메인 2차 QA에 따른 활동 멤버 관련 로직을 수정했습니다.
- 활동 멤버 직책 수정 시 리더가 1명 남은 경우 멤버로 변경할 수 없도록 제약
- 활동 그룹 참여자 정렬을 ACCEPTED, WAITING, REJECT 순으로 수정
- 스터디 삭제 권한을 super, admin, leader로 수정
- 리더가 **한 명**일 때, **리더**의 직책을 **멤버**로 바꾸려고 시도했을 때
- 활동 그룹 참여자 정렬
```
{
"data": {
"totalItems": 7,
"take": 7,
"items": [
{
"memberId": "202500004",
"memberName": "김채원",
"role": "NONE",
"status": "WAITING",
"applyReason": "백엔드에 관심이 있어서"
},
{
"memberId": "202014941",
"memberName": "송재훈",
"role": "LEADER",
"status": "ACCEPTED",
"applyReason": ""
},
{
"memberId": "202500001",
"memberName": "설윤",
"role": "MEMBER",
"status": "ACCEPTED",
"applyReason": "백엔드에 관심이 있어서"
},
{
"memberId": "202500002",
"memberName": "해원",
"role": …
```

refactor: 활동 관련 2차 QA에 따른 활동 멤버 관련 로직 수정 완료

---

src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
src/main/java/page/clab/api/global/common/file/api/FileController.java
src/main/java/page/clab/api/global/common/file/application/FileHandler.java
src/main/java/page/clab/api/global/common/file/application/FileService.java
src/main/java/page/clab/api/global/util/ImageUtil.java

> #531 
활동 2차 QA 후 파일 업로드 시 발생하는 최적화 예외 발생을 핸들링하고
추가적인 활동 관련 파일 업로드 API를 작성하고자 했습니다.
1. 파일 업로드 시 회전값을 사용한 최적화 로직에서 오류 발생할 경우 원본 이미지를 저장하도록 수정
2. 활동 카테고리의 NOTICE에서 사용할 파일 업로드 API 작성
3. 파일 업로드 API 내에서 ASSIGNMENT, SUBMIT의 불명확한 로직 재정립
1. 파일 업로드 시 orientation값이 없는 경우 예외를 발생시키고 500에러가 반환되었습니다.
이를 회전값 최적화 없이 원본 사진을 저장하고 log로 warning만 기록하도록 수정하였습니다.
수정 전
수정 후
경로로 접근한 파일
2. NOTICE, ASSIGNMENT, SUBMIT 관련 파일 업로드 API를 재정립했습니다.
ASSIGNMENT의 경우는 그룹장이 과제 양식을 올릴 때 사용할 수 있도록 activityGroupId만 파라미터로 받습니다.
SUBMIT의 경우는 그룹원이 과제를 제출 파일을 올릴 때 사용할 수 있도록 activityGroupId와 부모게시판인 ASSIGNMENT의 id 값을 parentBoardId로 전달하도록 했습니다.
- 그룹원이 NOTICE, ASSIGNMENT 관련 파일을 등록할 경우 아래와 같이 403 에러를 발생시킵니다
- 제출의 경우는 활동에 참여중인 그룹원만 아래와 같이 등록할 수 있습니다.
- SUBMIT 파일 업로드 시 부모 게시판의 카테고리가 ASSIGNMENT인지 판단하는 로직이 추가되었습니다.

refactor: 활동 관련 2차 QA에 따른 파일 업로드 로직 수정 완료

---

src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupMemberController.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
src/main/java/page/clab/api/domain/activity/activitygroup/domain/ActivityGroup.java
src/main/java/page/clab/api/domain/activity/activitygroup/exception/ContentLengthExceededException.java
src/main/java/page/clab/api/domain/activity/activitygroup/exception/CurriculumLengthExceededException.java
src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
src/main/resources/messages.properties

>#530
활동 생성 시 내용과 커리큘럼의 글자 수 제한 1000자로 수정하였습니다.
이슈에 있었던 남은 2가지 task는 @Jeong-Ag님과 운영진과 상의하여 프론트에서 수정하는 것으로 결정하였습니다.
- 활동 생성 시 내용과 커리큘럼의 글자 수 제한 1000자로 수정
코어팀 노션에 아래와 같이 새로운 예외에 대한 설명도 올려놨습니다.
**칼럼 제약사항 쿼리문**
```
ALTER TABLE activity_group
ALTER COLUMN content TYPE VARCHAR(1000),
ALTER COLUMN content SET NOT NULL,
ALTER COLUMN curriculum TYPE VARCHAR(1000);
```
내용이 1000자가 넘을 경우
커리큘럼이 1000자가 넘을 경우

refactor: 활동관련 2차 QA에 따른 활동 게시판 로직 수정 완료

---

src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationApplyService.java
src/main/java/page/clab/api/domain/hiring/application/domain/Application.java

> #540 
지원 알림에 모집 공고 명시하도록 수정하였습니다.
계획 단계에서는 `[CORE_TEAM]-` 형태로 명시하도록 했는데, 
@Jeong-Ag님과 결과물을 보면서 `[CORE_TEAM]` 로 명시하는 것이
더 가독성이 좋아 해당 형식으로 수정하였습니다.
- 지원 알림에 모집 공고 명시
기존에 생성된 알림내용의 경우, 바뀐 정책대로 데이터를 수정하고자 하였으나, 
Notification 테이블에는 모집 종류를 저장하는 칼럼이 없어 수정이 불가능했습니다.
앞으로 생성되는 지원 알림에 대해서만 해당 알림 생성규칙이 적용될 예정입니다.

refactor : 지원 알림에 모집 종류 명시하도록 수정

---

src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupAdminController.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
src/main/java/page/clab/api/domain/activity/activitygroup/dao/ActivityGroupRepository.java
src/main/java/page/clab/api/domain/activity/activitygroup/dao/ActivityGroupRepositoryCustom.java
src/main/java/page/clab/api/domain/activity/activitygroup/dao/ActivityGroupRepositoryCustomImpl.java
src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java

> #533 
활동 2차 QA에서 나온 활동 관리 이슈들을 수정했습니다.
1. 활동을 신청한 멤버의 리스트가 요청으로 들어오면 통합적으로 상태를 변경하는 api를 구현했습니다.
2. 스터디 종료 일자가 지날 시, 자동으로 상태를 `END`로 업데이트 해주는 스케줄러를 구현했습니다.
3. **내가 지원한 활동 목록 조회**, **나의 활동 목록 조회**, **활동 상태별 조회**에서 size를 변경해도, size에 따라 페이징 되지 않고 전체 데이터가 반환되는 현상을 수정했습니다.
- 활동 신청 멤버를 일괄 승인 할 수 있는 API 추가
- 스터디 종료 일자 후에 자동으로 상태를 END로 변경할 수 있도록 수정
- 활동 상태별 조회 시 페이징 미적용 문제 확인
`PageResponseDto`에서, 새로운 생성자를 추가했습니다. **내가 지원한 활동 목록 조회**, **나의 활동 목록 조회**, **활동 상태별 조회**에서 `List`를 매개변수로 받는 `PageResponseDto`생성자를 사용했었는데, 페이지네이션 되지 않은 `List`가 전달되어 전체 데이터가 반환되고 있었습니다.
하지만 `currentMemberId`로부터  `ActivityGroupMember`를 조회하여 해당 그룹 멤버의 활동을 가져오는 방식이기 때문에, `ActivityGroupMember`에 페이지네이션을 적용해봤자 이후에 필터링되는 과정에서 데이터가 달라지므로 기존의  **`List`를 매개변수로 받는 `PageResponseDto`생성자**를 사용할 수 없었습니다.
따라서, 같은 매개변수를 받지만 동작이 다른 생성자를 추가하게 …

refactor: 활동 관련 2차 QA에 따른 활동 관리 로직 수정 완료

---

src/main/java/page/clab/api/domain/activity/activitygroup/domain/ApplyForm.java
src/main/java/page/clab/api/domain/hiring/application/domain/Application.java
src/main/resources/messages.properties

> #542 
지원 동기 관련 글자 수 제한을 위한 수정 작업을 진행했습니다.
랜딩페이지의 모집공고에 지원하는 경우와 활동에 지원하는 경우 두 가지를 수정하였습니다.
- 활동 지원동기 1000자로 설정
- 랜딩페이지 모집공고 지원동기 1000자로 설정
**칼럼 제약 사항 수정 쿼리문**
```
ALTER TABLE application
ALTER COLUMN other_activities TYPE VARCHAR(1000),
ALTER COLUMN other_activities SET NOT NULL;
ALTER TABLE apply_form
ALTER COLUMN apply_reason TYPE VARCHAR(1000);
```

refactor: 지원 관련 글자수 제한 설정

---

src/main/java/page/clab/api/domain/activity/activitygroup/domain/ActivityGroup.java
src/main/resources/messages.properties

> #548 
활동 그룹의 커리큘럼 글자 수 `min` 값을 제거했습니다.(`default = 0`)
따라서, 커리큘럼에 아무 것도 적지 않아도 정상적으로 그룹이 생성됩니다.
- `curriculum` 필드의 `size`어노테이션 `min`값 제거

refactor: 활동 그룹 커리큘럼 글자 수 조정 완료

---

src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupMemberController.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
src/main/java/page/clab/api/domain/activity/activitygroup/dao/ActivityGroupRepositoryCustomImpl.java

> #549 
`나의 활동 목록 조회`, `활동 상태별 조회`, `내가 지원한 활동 목록 조회` api 의 응답인 활동 그룹 목록의 정렬을 아래와 같이 변경했습니다.
- 정렬 기준 : `createdAt`
- 정렬 방향 : `desc` 
- 활동 그룹 목록을 반환하는 api들의 응답값을 `createdAt` 기준 `desc` 방향으로 정렬
수정 전과 수정 후의 response 값을 기록했었는데, 테스트했던 response 값이 길어 Screenshot이 아닌 텍스트 형식으로 기록했습니다.
- 내가 지원한 활동 목록 조회 (수정 전)
```json
{
"data": {
"totalItems": 2,
"take": 2,
"items": [
{
"id": 6,
"name": "게임 스터디",
"content": "게임 스터디",
"category": "STUDY",
"subject": "1학년 이상",
"imageUrl": "https://i.namu.wiki/i/KcqDuQYTxNpUcLIMZTg28QXse0XiWx1G7K68kYYCo1GuhoHmhB_V8Qe9odGGt0BH9-0nQZTN53WXTNpDmwVfWQ.svg",
"leaders": [
{
"id": "202014941",
"name": "송재훈"
},
{
"id": "202500001",
"name": "설윤"
}
],
"participantCount": 5, …
```

refactor: 활동 그룹 목록을 가장 최신에 생성된 순으로 정렬되도록 변경 완료

---

src/main/java/page/clab/api/domain/activity/activitygroup/dao/ActivityGroupDetailsRepositoryImpl.java

> #552 
활동 상세 조회 API에서 groupMembers를 담아서 반환할 때 실제로 참여중인 멤버만 반환하도록 수정하였습니다.
- 활동 상세 조회 시 ACCEPTED인 멤버만 groupMembers에 담도록 수정
- 수정하고자 하는 메소드가 활동 상세 조회 시에만 사용되고 있음을 확인했습니다. 혹시 다른 API의 응답 생성 시 영향을 미칠까봐 확인하였어요.
- NONE이고 WATING인 멤버는 응답에 포함되지 않습니다.
- MEMBER이고 REJECTED된 멤버는 즉 활동하다가 퇴출된 멤버는 응답에 포함되지 않습니다.
-ACCEPTED인 멤버만 응답에 포함됩니다.

refactor: 활동 상세 조회 응답에서 실제 참여인원만 반환하도록 수정 완료

---

src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java

> #561 
활동 삭제시 활동에 참여하지 않은 admin도 삭제가 가능하도록 변경했습니다.
- 활동에 참여하지 않은 admin과 해당 활동의 Leader가 활동 삭제를 할 수 있도록 변경
활동 삭제 시 사용하던 `validateLeaderPermission()`메서드에서 `GroupLeader`를 조회할 때 활동에 참여하지 않은 `admin`일 경우 `NotFoundException`을 던졌었는데, `validateLeaderPermission()`을 변경하게 되면서 연관되어 있던 다른 메서드의 권한 검사도 변경되게 되었습니다.
변경된 기능은 다음과 같습니다.
- 활동 수정, 활동 삭제, 프로젝트 진행 수정, 일정 등록, 활동 멤버 지원서 조회, 멤버 상태 변경, 멤버 직책 변경 
위의 기능들은 전부 admin도 가능해야 할 일이라고 생각되어 변경된 상태로 놔뒀는데, 잘 살펴봐주시면 감사하겠습니다.

refactor: 활동 3차 QA에 따른 활동 그룹 관련 기능 수정 완료

---

src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java

> #562 
활동에 신청한 멤버의 상태를 변경할 경우, 해당 멤버에게 알림이 가는 로직이 있습니다.
이때 기존에는 어떤 활동인지 활동명이 명시되지 않아 불편하여 활동명을 알림 문구에
추가하는 작업을 진행했습니다.
- 스터디 거절과 승인 시 어떤 스터디 인지 알림에 명시
@Jeong-Ag님과 @SongJaeHoonn님과 상의해서 알림 문구를 수정하였습니다!
- 기존 알림 문구
- 개선된 알림 문구

refactor: 3차 QA에 따른 활동 관련 알림 수정 완료

---

src/main/java/page/clab/api/domain/memberManagement/member/adapter/out/persistence/MemberRepositoryImpl.java

> #570
이달의 생일자 조회 API에서 정렬 기준에 `birth`가 있는 경우 년도와 월을 무시하고 `일`을 기준으로 정렬하는 로직을 개선했습니다. 기존에는 `yyyy-MM-dd` 형식으로 정렬되었기 때문에 년도에 의해 조회 결과가 의도와 다르게 나왔으나, 이번 수정에서는 `일`을 기준으로 정확하게 정렬되도록 변경했습니다.
- 정렬 기준이 birth인 경우 `일`을 기준으로 정렬하도록 설정
- 정렬 기준이 여러 개인 경우 정렬 순서를 보장
```json
{
"data": {
"totalItems": 7,
"take": 7,
"items": [
{
"id": "202310000",
"name": "홍길동",
"birth": "2004-01-01",
"imageUrl": "https://www.clab.page/assets/dongmin-860f3a1e.jpeg"
},
{
"id": "202112000",
"name": "홍길동",
"birth": "2000-01-01",
"imageUrl": null
},
{
"id": "201912156",
"name": "홍길동",
"birth": "2004-01-07",
"imageUrl": "https://www.clab.page/assets/dongmin-860f3a1e.jpeg"
},
{
"id": "202310001",
"name": "홍길동",
"birth": "2004-01-09", …
```

refactor: 이달의 생일자 조회 API 정렬 로직 개선 완료

---

src/main/java/page/clab/api/domain/memberManagement/member/application/event/ApplicationMemberCreatedProcessor.java
src/main/java/page/clab/api/domain/memberManagement/member/application/service/MemberPasswordManagementService.java
src/main/java/page/clab/api/domain/memberManagement/member/application/service/MemberRegisterService.java
src/main/java/page/clab/api/global/common/email/application/EmailAsyncService.java
src/main/java/page/clab/api/global/common/email/application/EmailService.java
src/main/java/page/clab/api/global/common/email/domain/EmailTemplateType.java
src/main/java/page/clab/api/global/common/email/dto/request/EmailDto.java
src/main/java/page/clab/api/global/config/EmailTemplateProperties.java
src/main/resources/templates/clabEmail.html

> #559 
기존의 하드코딩된 이메일 내용을 YAML 파일로 이동하고, 비밀번호 재설정 관련 메일 전송 메소드를 개선했습니다. 이메일 템플릿 관리의 유연성을 높이고 코드에서 템플릿 변경 없이 YAML에서 쉽게 수정할 수 있도록 개선하였습니다.
- 이메일 전송 메소드에서 이메일 내용 하드코딩을 제거하고, YAML에서 이메일 템플릿을 불러오는 방식으로 수정
- YAML 파일에 `new-password` 템플릿을 추가
- `EmailService`의 템플릿 로직을 `EmailTemplateProperties`를 사용하여 동적으로 이메일 내용을 불러오도록 리팩토링
- 이메일 템플릿에 기재된 동아리 소속명 수정
```yaml
email:
templates:
account-creation:
subject: "C-Lab 계정 발급 안내"
content: |
정식으로 C-Lab의 일원이 된 것을 축하드립니다.
C-Lab과 함께하는 동안 불타는 열정으로 모든 원하는 목표를 이루어 내시기를 바라고,
훗날, 당신의 합류가 C-Lab에겐 최고의 행운이었다고 기억되기를 희망합니다.
로그인을 위해 아래의 계정 정보를 확인해주세요.
ID: {{id}}
Password: {{password}}
로그인 후 비밀번호를 변경해주세요.
password-reset-code:
subject: "C-Lab 비밀번호 재발급 인증 안내"
content: |
C-Lab 비밀번호 재발급 인증 안내 메일입니다.
인증번호는 {{code}}입니다.
해당 인증번호를 비밀번호 재설정 페이지에 입력해주세요.
재설정시 비밀번호는 인증번호로 대체됩니다. …
```

refactor: 이메일 템플릿 하드코딩 개선 및 외부 관리로 전환 완료

---

src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupAdminController.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepository.java
src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepositoryCustom.java
src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepositoryImpl.java
src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
src/main/java/page/clab/api/global/util/PaginationUtils.java

> #577 
`활동 멤버 및 지원서 조회` api에서, 페이지에서만 정렬되도록 하는 것이 아닌, 전체 데이터를 대상으로 정렬을 한 후 페이지가 나눠지도록 변경했습니다.
또한, 정렬 시 리더가 최상단에 위치할 수 있도록 `PagedResponseDto`에 새로운 생성자를 만들고, 그에 따른 변경점을 수정했습니다.
작업 도중, `내가 지원한 활동 목록 조회`, `나의 활동 목록 조회`에서도 같은 문제를 발견해 수정했습니다.
해당 변경들은 프론트엔드 및 운영진분과 함께 의논하여 문제를 발견하고, 수정했습니다.
- 전체 데이터를 대상으로 정렬하도록 변경
- 리더가 최상단에 위치할 수 있도록 변경
```
{
"data": {
"totalItems": 4,
"take": 4,
"items": [
{
"memberId": "leader",
"memberName": "리더",
"role": "LEADER",
"status": "ACCEPTED",
"applyReason": ""
},
{
"memberId": "202500001",
"memberName": "설윤",
"role": "NONE",
"status": "WAITING",
"applyReason": "백엔드에 관심이 있어서"
},
{
"memberId": "202500003",
"memberName": "김민지",
"role": "MEMBER",
"status": "ACCEPTED", …
```

refactor: 활동 멤버 및 지원서 조회 정렬 로직 변경 완료

---

src/main/java/page/clab/api/global/auth/filter/InvalidEndpointAccessFilter.java
src/main/java/page/clab/api/global/util/ApiLogger.java
src/main/java/page/clab/api/global/util/SecurityPatternChecker.java

> #582 
비정상적인 접근 패턴 탐지와 슬랙 알림 전송 관련 코드를 리팩토링하였습니다. 이번 리팩토링을 통해 불필요한 슬랙 알림을 줄이고, 최초 비정상적인 접근 시에만 알림이 전송되도록 변경하였습니다. 또한, 코드의 가독성과 유지보수성을 높였습니다.
- **슬랙 알림 전송 로직 변경**
- 최초 비정상적인 접근 시에만 슬랙 알림을 전송하고, 이후 동일한 IP에 대해서는 슬랙 알림을 전송하지 않도록 변경하였습니다.
- **비정상적인 접근 패턴 탐지 코드 분리**
- `SecurityPatternChecker` 클래스를 통해 의심스러운 경로 패턴 탐지를 담당하도록 코드 분리.
- **`InvalidEndpointAccessFilter` 리팩토링**
- 중복된 슬랙 알림 전송 로직을 하나로 통합.
- `handleSuspiciousAccess`, `logSuspiciousAccess` 등으로 메소드를 분리하여 단일 책임 원칙을 준수하도록 개선.
- 코드 내 상수화 및 메소드 분리로 가독성 및 유지보수성 향상.
- 이번 리팩토링을 통해 비정상적인 접근에 대한 알림이 불필요하게 중복되지 않으며, 보안 패턴 검사가 더욱 명확하게 처리됩니다.

refactor: 비정상적인 서버 접근 시 슬랙 알림 전송 로직 수정 완료

---

src/main/resources/application.yml

> #587 
이메일 템플릿 관련 설정을 YAML 파일로 이동하는 작업에서, 외부 공개 프로파일 `application.yml`에 대한 수정이 누락되었습니다. 이로 인해 YAML 파일에서 이메일 템플릿을 로드하는 설정이 정상적으로 적용되지 않는 문제를 수정합니다.
- **외부 공개 프로파일(application.yml) 수정**
- 이메일 템플릿 로드 경로가 제대로 설정되지 않은 부분을 수정하여, 이메일 전송 시 YAML 파일에서 템플릿을 정상적으로 로드할 수 있도록 설정을 추가.
```yaml
email:
templates:
account-creation:
subject: "C-Lab Account Creation Notice"
content: |
Congratulations on becoming an official member of C-Lab!
During your time with C-Lab, we hope that you achieve all your desired goals with burning passion,
and in the future, we hope that your joining C-Lab will be remembered as one of our greatest fortunes.
Please review the account details below to log in:
ID: {{id}}
Password: {{password}}
Please change your password after logging in.
password-reset-code:
subject: "C-Lab …
```

fix: 외부 공개 프로파일(application.yml)의 이메일 템플릿 설정 누락 수정 완료

---

src/main/java/page/clab/api/global/filter/PostResponseFilter.java

> #592 
`POST` 요청의 응답 상태 코드를 변경하는 필터를 추가했습니다.
이 필터는 `/api/*` 경로에 대한 `POST` 요청의 응답 상태 코드가 200일 경우 이를 `201`로 수정합니다.
- `/api/*` 경로의 모든 `POST` 요청을 대상으로 `HttpServletResponse`의 상태 코드가 200일 경우 `201`로 변경하도록 하는 서블릿 필터 추가
**POST**
```bash
INFO  page.clab.api.global.util.ApiLogger - [0:0:0:0:0:0:0:1:test] /api/v1/recruitments POST 201 79ms
INFO  page.clab.api.global.util.ApiLogger - [0:0:0:0:0:0:0:1:test] /api/v1/books POST 201 27ms
INFO  page.clab.api.global.util.ApiLogger - [0:0:0:0:0:0:0:1:test] /api/v1/awards POST 201 34ms
INFO  page.clab.api.global.util.ApiLogger - [0:0:0:0:0:0:0:1:test] /api/v1/awards POST 201 4ms
```
**POST 외 메소드**
```bash
INFO  page.clab.api.global.util.ApiLogger - [0:0:0:0:0:0:0:1:test] /api/v1/awards?page=0&size=20&sortBy=awardDate&sortDirection=desc GET 200 110ms
INFO …
```

refactor: POST 요청 응답 상태코드 변경 (200 → 201) 완료

---

src/main/java/page/clab/api/domain/community/board/domain/Board.java
src/main/java/page/clab/api/domain/community/board/domain/BoardCategory.java

> #606 
[작업 동기]
사용하지 않는 게시판 카테고리를 삭제하고 용도에 맞게 재분류하교자 합니다. 
이 내용은 2024 C-Lab 운영진의 씨랩 페이지 커뮤니티 활성화 방안 내용 중 백엔드 파트@SongJaeHoonn 프론트 파트 @Jeong-Ag과 함께 작업 계획을 세운 내용입니다.
[작업 내용]
아래와 같은 카테고리로 게시판을 분류합니다.
**공지사항 게시판 (NOTICE)
자유게시판 (FREE)
개발 질문 게시판 (DEVELOPMENT_QNA)
정보 및 후기 게시판 (INFORMATION_REVIEWS)**
따라서 졸업생 게시판과 QnA게시판이 삭제되고
개발질문 게시판과 정보 및 후기 게시판이 생성됩니다.
이때 **QnA 게시판에 등록된 글들은 자유게시판으로 옮기도록 합니다.**
- boardCategory Enum 재설정
- QnA 게시판의 data 수정 SQL문 작성
**QnA 게시판에 등록된 글들을 자유게시판으로 옮기기 위한 SQL문**  
```
UPDATE board
SET category = 'FREE'
WHERE category = 'QNA';
```
**Board 테이블의 제약조건 삭제 후 재설정을 위한 SQL문**
```
ALTER TABLE board
DROP CONSTRAINT board_category_check;
ALTER TABLE board
ADD CONSTRAINT board_category_check 
CHECK (category::text = ANY (ARRAY['NOTICE'::character varying::text, 
'FREE'::character …
```

refactor: 게시판 카테고리 재분류 완료

---

.dockerignore
build.gradle
gradle/wrapper/gradle-wrapper.properties
jenkins/prod/Dockerfile
jenkins/prod/Jenkinsfile
jenkins/stage/Dockerfile
jenkins/stage/Jenkinsfile

> #616 
기존의 단일 단계 Docker 빌드 방식의 한계를 극복하고, 빌드 속도 및 이미지 크기를 최적화하기 위해 **Docker Multi-stage Builds**, **Spring Layered JAR**, **Docker BuildKit**을 도입하였습니다. 또한, Jenkins CD 파이프라인을 최적화하여 전체적인 CD 효율성을 향상시켰습니다. 이를 통해 더 작고 안전한 Docker 이미지를 생성하고, 빌드 시간을 단축하며, 유지 관리성을 높일 수 있게 되었습니다.
- **멀티 스테이지 빌드 적용**
- 빌드 환경과 런타임 환경을 분리하여 단계별 최적화
- 빌드 스테이지: 빌드 도구 및 종속성을 포함한 빌드 환경 구성
- 런타임 스테이지: 최소한의 런타임 구성 요소만 포함한 경량 이미지 생성
- **Spring Layered JAR 도입**
- Spring Boot의 Layertools를 활용하여 JAR 파일을 레이어별로 분리
- Dockerfile에서 레이어별로 필요한 파일만 복사하여 캐싱 효율성 증대
- **Docker BuildKit 활성화 및 최적화**
- 환경 변수 설정을 통해 BuildKit을 기본 빌드 도구로 활성화
- **Jenkins CD 파이프라인 최적화**
- 불필요한 작업 제거: 빌드 및 배포 과정에서 중복되거나 불필요한 단계를 식별하고 제거
- 병렬화 도입: 가능한 작업을 병렬로 실행하여 전체 빌드 및 배포 시간을 단축
- 캐시 활용 강화: 이전 빌드의 아티팩트 및 캐시를 효과적으로 재사용하여 빌드 시간을 줄임
- **Dockerfile 및 Jenkinsfile …

refactor: CD 파이프라인 이미지 최적화 및 빌드 성능 개선을 위한 Docker Multi-stage Build, Spring Layered JAR 및 BuildKit 도입 완료

---

jenkins/prod/Jenkinsfile
jenkins/prod/config.yml
jenkins/stage/Jenkinsfile
jenkins/stage/config.yml

> #624
알림 시스템을 개선하여 다중 플랫폼을 지원하도록 했습니다. Config YAML 설정에 따라 알림 플랫폼을 유동적으로 선택할 수 있게 되어, 유연한 알림 전송이 가능해졌습니다.
- **Config YAML 구조 수정**
- Slack 및 Discord 설정을 분리하여 알림 플랫폼을 명시적으로 구분.
- 새로운 플랫폼이 추가될 경우 확장 가능한 구조로 설계.
- **알림 전송 로직 리팩터링**
- Slack 전용 `sendSlackBuildNotification` 메서드를 일반화하여 다중 플랫폼 지원.
- 플랫폼별 알림 생성 로직을 분리하여 각 플랫폼에 적합한 메시지 포맷 생성.
- **플랫폼별 메시지 포맷 구현**
- **Slack:** 기존 JSON 포맷 유지.
- **Discord:** Embed 형태의 알림 포맷 작성.
- **유동적인 플랫폼 선택**
- Config YAML에서 활성화된 플랫폼을 확인하여 해당 플랫폼에 알림을 전송하도록 구현.
Slack과 Discord 모두 알림이 정상적으로 동작하는 것을 확인했습니다.
**기존**
```yaml
slack:
webhook-url: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX" # Slack webhook URL
color-success: "#F2C744" # Slack message color for success
color-failure: "#8D1E0E" # Slack message color for failure
```
**변경** …

refactor: Jenkins Config YAML 기반 알림 플랫폼 유동적 지원 추가 완료

---

jenkins/prod/Jenkinsfile
jenkins/prod/config.yml
jenkins/stage/Jenkinsfile
jenkins/stage/config.yml

스쿼시 머지로 진행해야 했는데, 일반 머지로 진행해서 revert 합니다.

Revert "refactor: Jenkins Config YAML 기반 알림 플랫폼 유동적 지원 추가 완료"

---

src/main/java/page/clab/api/domain/community/board/adapter/in/web/BoardEmojiToggleController.java
src/main/java/page/clab/api/domain/community/board/application/dto/mapper/BoardDtoMapper.java
src/main/java/page/clab/api/domain/community/board/application/dto/mapper/BoardEmojiDtoMapper.java
src/main/java/page/clab/api/domain/community/board/application/dto/response/BoardEmojiToggleResponseDto.java
src/main/java/page/clab/api/domain/community/board/application/port/in/ToggleBoardEmojiUseCase.java
src/main/java/page/clab/api/domain/community/board/application/service/BoardEmojiToggleService.java
src/main/java/page/clab/api/domain/community/comment/adapter/in/web/CommentLikeToggleController.java
src/main/java/page/clab/api/domain/community/comment/application/dto/mapper/CommentLikeDtoMapper.java
src/main/java/page/clab/api/domain/community/comment/application/dto/response/CommentLikeToggleResponseDto.java
src/main/java/page/clab/api/domain/community/comment/application/port/in/ToggleCommentLikeUseCase.java
src/main/java/page/clab/api/domain/community/comment/application/service/CommentLikeToggleService.java

> #633 
게시글 이모지와 누르기/취소하기 API와
댓글 좋아요 누르기/취소하기 API에서 기존 응답 방식을 수정했습니다.
**기존에는 아래와 같이 응답이 되었습니다.**
게시글 이모지 누르기/취소하기 API : board category 반환
댓글 좋아요 누르기/취소하기 API : 댓글의 총 좋아요 개수 반환
**이를 아래와 같이 응답하도록 수정했습니다.**
게시글 이모지 누르기/취소하기 API :
댓글 좋아요 누르기/취소하기 API :
- 게시글 이모지 클릭 토글 API 응답 수정
- 댓글 좋아요 클릭 토글 API 응답 수정
1. 해당 작업에서 CommentLike 테이블의 경우 소프트딜리트가 적용되지 않음을 확인했습니다.
댓글의 좋아요와 게시글의 이모지는 비슷한 로직임에도 게시글의 이모지만 소프트딜리트가 적용되어 있었습니다.
따라서 누르기/취소하기 토글 행위에 대해 어떤 딜리트 방식이 효율적일지 성능 테스트를 #634 에서 진행하고 개선하도록 하겠습니다.
2. @limehee님께서 댓글에서도 좋아요 대신 이모지를 사용하는 것을 제안해주셨습니다. 해당 부분은 members 프로젝트에서 현재 기획한 신규 기능을 마무리하고 추가 회의를 통해 다시 다루도록 @Jeong-Ag 님과 이야기 나눴습니다. 댓글 이모지 기능으로 노선을 수정할 경우, 핫게시글 선정 방식의 수정과 프론트에서 게시글 옆에 [댓글개수]를 표현하는 방식에 대해서도 추가 수정이 필요한 점이 있었습니다. 이러한 이유로 신규 기능 출시를 먼저 하고, 추후 다시 다뤄보도록 하겠습니다. 좋은 의견 감사합니다.

refactor : 게시글 이모지와 댓글 좋아요 누르기/취소하기 API 응답 DTO 반환하도록 수정

---

src/main/java/page/clab/api/domain/community/board/application/dto/mapper/BoardEmojiDtoMapper.java
src/main/java/page/clab/api/domain/community/board/application/dto/response/BoardEmojiToggleResponseDto.java
src/main/java/page/clab/api/domain/community/board/application/service/BoardEmojiToggleService.java
src/main/java/page/clab/api/domain/community/board/domain/BoardCategory.java

> #638 
@Jeong-Ag 님이 API 연동 중에 요청하신 수정사항 반영했습니다.
- 게시글 이모지 누르기/취소하기 api 응답에 board category 추가

refactor : 게시글 이모지 누르기/취소하기 api 응답에서 board category 추가

---

src/main/java/page/clab/api/domain/community/board/domain/BoardCategory.java

> #640 
#609  이후로 백엔드에서 관리하는 ENUM의 key 값은 대문자 + 스네이크로 통일할 예정입니다. 현재는 진행 중인 연동 작업 때문에 BoardCategory의 key 표현만 소문자 + 스네이크로 잠시 롤백합니다.
- BoardCategory의 key 표현 방식 소문자 + 스네이크로 롤백

refactor : BoardCategory의 key 표현 방식 소문자 + 스네이크로 롤백

---

src/main/java/page/clab/api/domain/memberManagement/executive/adapter/in/web/ExecutiveRetrievalController.java
src/main/java/page/clab/api/global/config/SecurityConstants.java

> #653 
운영진 정보 조회 API의 요청 권한을 `GUEST`에서 `ANONYMOUS`로 변경했습니다.
- 운영진 정보 조회 권한 변경

refactor: 운영진 정보 조회 API 권한 변경 완료

---

src/main/java/page/clab/api/domain/hiring/recruitment/adapter/in/web/OpenRecruitmentsRetrievalController.java
src/main/java/page/clab/api/domain/hiring/recruitment/adapter/out/persistence/RecruitmentPersistenceAdapter.java
src/main/java/page/clab/api/domain/hiring/recruitment/adapter/out/persistence/RecruitmentRepository.java
src/main/java/page/clab/api/domain/hiring/recruitment/application/dto/mapper/RecruitmentDtoMapper.java
src/main/java/page/clab/api/domain/hiring/recruitment/application/dto/response/RecruitmentOpenResponseDto.java
src/main/java/page/clab/api/domain/hiring/recruitment/application/port/in/RetrieveOpenRecruitmentsUseCase.java
src/main/java/page/clab/api/domain/hiring/recruitment/application/port/out/RetrieveRecruitmentPort.java
src/main/java/page/clab/api/domain/hiring/recruitment/application/service/OpenRecruitmentsRetrievalService.java
src/main/java/page/clab/api/global/config/SecurityConstants.java

> #657 
현재 모집 중인(`RecruitmentStatus.OPEN`) 모집 공고들을 조회할 수 있는 기능을 구현했습니다.
- 현재 모집중인 모집공고 목록 조회 API 작성
- 모집 종료일이 지나지 않았을 때
- 새로운 모집 공고를 추가했을 때

feat: 현재 모집중인 모집공고 목록 조회 기능 구현 완료

---

src/main/java/page/clab/api/domain/hiring/recruitment/adapter/in/web/RecruitmentRemoveController.java
src/main/java/page/clab/api/domain/hiring/recruitment/application/port/in/RemoveRecruitmentUseCase.java
src/main/java/page/clab/api/domain/hiring/recruitment/application/service/RecruitmentRemoveService.java
src/main/java/page/clab/api/domain/hiring/recruitment/domain/Recruitment.java

> #659 
모집 공고 id를 받아 삭제하는 기능을 구현했습니다.
- 모집공고 id로 삭제하기 API 작성
- 삭제 전 모집 공고 조회
- id 3번 삭제 후 모집 공고 조회

feat: 모집 공고 삭제 기능 구현 완료

---

src/main/java/page/clab/api/global/common/file/api/FileController.java
src/main/java/page/clab/api/global/common/file/application/FileService.java

> #661 
운영진 사진 업로드 경로를 다음과 같이 변경했습니다.
기존 : `/executives/{currentUserId}/`
변경 후 : `/executives/{executiveId}/`
- 경로 생성시 `executives` 디렉토리인지 체크 
- 운영진 사진 저장 디렉토리 구조 변경
운영진 사진을 한번에 받아 한 명이 전부 등록할 때, 사진이 삭제되지 않고 운영진 학번으로 저장됩니다.

refactor: 운영진 사진 업로드 디렉토리 구조 변경 완료

---

src/main/java/page/clab/api/domain/memberManagement/member/adapter/out/persistence/MemberRepositoryImpl.java

#665
이달의 생일자 조회 시 관리자와 게스트 정보는 제외하도록 where 구문을 수정했습니다.
- 이달의 생일자 조회 시 관리자와 게스트 정보 제외
실제 서버의 data를 dump 하여 테스트를 진행했습니다.
원래는 아래처럼 관리자와 방문자가 맨 앞에 조회 되었으나 Screenshot에 첨부된 JSON 응답 처럼 실제 멤버부터 조회되는 것을 확인 할 수 있습니다.

refactor : 이달의 생일자 조회 시 관리자와 게스트 정보 제외 완료
